### ISSUE TITLE
.searchTrack does not return any response if no matching tracks are found.

### ISSUE THREAD

**Issue by singhketan** [ddanninger/node-gracenote#2]
I've tried both the request modes. No response at all.

**Comment by singhketan** [comment]
I've corrected the problem in my branch. Update the method '_getOETElem' at line 221 in Gracenote.js. Added a check if the 'root' variable was undefined. The whole thing was stopping when say a song didn't return a genre array.

**Comment by webmelzer** [comment]
Thank you, I was having the same issue. Update from singhketan seems to resolve. Please merge with master.
