### ISSUE TITLE
Which runtime support the root||{} syntax?

### ISSUE THREAD

**Issue by baoshan** [ddanninger/node-gracenote#4]
I noticed an unsupported syntax:

`function (root||{}) {...}`

https://github.com/ddanninger/node-gracenote/blob/master/lib/Gracenote.js#L237

I wonder if this is a typo or an ES 6/7 syntax?

**Comment by ddanninger** [comment]
I beleive it is a supported syntax , a binary logical operator. Which should be supported in ES 5 (not 100% sure) but for sure in ES 6. - http://ariya.ofilabs.com/2013/02/es6-and-default-argument.html 

Tell me if iam wrong here and send a pull request then =)

**Comment by baoshan** [comment]
I'm new to ES5/6/(7?).

I tried node.js 5.3 and babel preset 2015, both hint the `logic or default` syntax is unsupported.

What transpiler do you use?

**Comment by ddanninger** [comment]
#5 closed this issue
